import { Head } from '@inertiajs/react';

export default function PublicLayout({ children, branding = {} }) {
    const companyName = branding.company_name || 'BacklinkPro';
    const accentColor = branding.accent_color || '#2E2E2E';
    const logoUrl = branding.logo_url;

    return (
        <div className="min-h-screen bg-gray-50">
            <Head title={companyName} />
            
            {/* Header */}
            <header className="bg-white border-b border-gray-200">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center">
                            {logoUrl ? (
                                <img src={logoUrl} alt={companyName} className="h-8 w-auto" />
                            ) : (
                                <h1 className="text-xl font-bold" style={{ color: accentColor }}>
                                    {companyName}
                                </h1>
                            )}
                        </div>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                {children}
            </main>

            {/* Footer */}
            <footer className="bg-white border-t border-gray-200 mt-12">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                    <p className="text-center text-sm text-gray-500">
                        Report generated by {companyName}
                    </p>
                </div>
            </footer>
        </div>
    );
}


