<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your SEO Audit Report is Ready</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .logo {
            max-width: 200px;
            margin-bottom: 20px;
        }
        .score {
            font-size: 48px;
            font-weight: bold;
            color: {{ $branding->primary_color ?? '#4299e1' }};
            margin: 20px 0;
        }
        .button {
            display: inline-block;
            padding: 12px 24px;
            background-color: {{ $branding->primary_color ?? '#4299e1' }};
            color: #fff;
            text-decoration: none;
            border-radius: 6px;
            margin: 20px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #718096;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        @if($branding && $branding->logo_path)
            <img src="{{ asset('storage/' . $branding->logo_path) }}" alt="{{ $branding->brand_name ?? 'Logo' }}" class="logo">
        @endif
        <h1>Your SEO Audit Report is Ready</h1>
    </div>

    <p>Hello,</p>

    <p>Your SEO audit for <strong>{{ $audit->url }}</strong> has been completed.</p>

    @if($audit->overall_score)
        <div style="text-align: center;">
            <div class="score">{{ $audit->overall_score }}</div>
            <p>Overall Grade: <strong>{{ $audit->overall_grade }}</strong></p>
        </div>
    @endif

    <div style="text-align: center;">
        <a href="{{ $reportUrl }}" class="button">View Full Report</a>
    </div>

    <div class="footer">
        @if($branding && $branding->report_footer_text)
            <p>{{ $branding->report_footer_text }}</p>
        @elseif(!$branding || !$branding->hide_backlinkpro_branding)
            <p>Generated by BacklinkPro</p>
        @endif
    </div>
</body>
</html>
