<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your SEO Audit Report is Ready</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; max-width: 600px; margin: 0 auto; padding: 24px; }
        .header { text-align: center; margin-bottom: 24px; }
        .score { font-size: 42px; font-weight: bold; color: #7C3AED; margin: 16px 0; }
        .button { display: inline-block; padding: 12px 24px; background: #7C3AED; color: #fff !important; text-decoration: none; border-radius: 12px; font-weight: 600; margin: 16px 0; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; text-align: center; }
        .url { word-break: break-all; color: #7C3AED; font-weight: 600; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Your SEO Audit Report is Ready</h1>
    </div>
    <p>Hello,</p>
    <p>Your SEO audit for <span class="url">{{ $audit->url }}</span> has been completed.</p>
    @if($audit->overall_score !== null)
        <div style="text-align: center;">
            <div class="score">{{ $audit->overall_score }}</div>
            <p>Overall Grade: <strong>{{ $audit->overall_grade ?? '—' }}</strong></p>
        </div>
    @endif
    <div style="text-align: center;">
        <a href="{{ $reportUrl }}" class="button">View Full Report</a>
    </div>
    <div class="footer">
        <p>Generated by BacklinkPro</p>
    </div>
</body>
</html>
